# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "cryptd" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelPackages = pkgs.linuxPackages_6_6;

  fileSystems = let
    mkBtrfsSubvol = subvol: {
      device = "/dev/disk/by-label/NIXOS_ROOT";
      fsType = "btrfs";
      options = [ "subvol=${subvol}" "compress=zstd:1" "noatime" "space_cache=v2" "discard=async" ];
    };
  in
  {
    "/" = mkBtrfsSubvol "@";
    "/home" = mkBtrfsSubvol "@home";
    "/nix" = mkBtrfsSubvol "@nix";
    "/.snapshots" = mkBtrfsSubvol "@snapshots";

    "/boot" = {
      device = "/dev/disk/by-label/SYSTEM";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  };

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-label/NIXOS_LUKS";
    preLVM = true;
    allowDiscards = true;
  };

  swapDevices =
    [ { device = "/dev/disk/by-label/NIXOS_SWAP"; }
    ];

  # Enable zram
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;  # Use 50% of RAM for compressed swap
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
