{ pkgs, lib, ... }:

let
  emacsPackages = [ pkgs.emacsPackages.jinx ];
in
{
  homebrew.casks = [ "jimeh/emacs-builds/emacs-app" ];

  home-manager.sharedModules = [
    {
      home = {
        file = {
          ".config/emacs/early-init.el".source = ./early-init.el;
          ".config/emacs/init.el".source = ./init.el;

          ".config/emacs/nix-emacs.el".text = ''
            ;;; nix-emacs.el --- Auto-generated; do not edit -*- lexical-binding: t -*-
            ;; Generated by home-manager. Lists Nix store paths whose elpa directories
            ;; should be added to `load-path' so a non-Nix Emacs (Homebrew here) can
            ;; find packages installed via Nix.

            (defvar mzacuna/nix-emacs-roots
              '(${lib.concatMapStringsSep "\n        " (p: ''"${p}"'') emacsPackages}))

            (dolist (root mzacuna/nix-emacs-roots)
              (let ((elpa-dir (expand-file-name "share/emacs/site-lisp/elpa" root)))
                (when (file-directory-p elpa-dir)
                  (dolist (subdir (directory-files elpa-dir t "\\`[^.]"))
                    (when (file-directory-p subdir)
                      (add-to-list 'load-path subdir))))))

            (provide 'nix-emacs)
          '';
        };

        packages = emacsPackages ++ [
          pkgs.emacs-lsp-booster
        ];
      };
    }
  ];
}
